apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-demo
spec:
  selector:
    matchLabels:
      app: gateway-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-demo
    spec:
      containers:
        - name: gateway-demo
          image: leonardorocha1990/gateway_demo:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PI_DB_HOST
              value: pi-mariadb
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password