apiVersion: v1
kind: Service
metadata:
  name: pi-mariadb
  labels:
    app: pi-mariadb
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30306
      name: pi-mariadb
  selector:
    app: pi-mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: pi-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-mariadb
  labels:
    app: pi-mariadb
spec:
  selector:
    matchLabels:
      app: pi-mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pi-mariadb
    spec:
      containers:
        - image: jsurf/rpi-mariadb
          name: pi-mariadb
          env:
            - name: MYSQL_USER
              value: pi
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: pi-mariadb
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mariadb
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim