apiVersion: v1
kind: Service
metadata:
  name: gateway-demo
  labels:
    app: gateway-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: gateway-demo
  selector:
    app: gateway-demo